export const chatHistories = [
  { id: 1, title: "Previous conversation 1", date: "Today" },
  { id: 2, title: "Help with React component", date: "Today" },
  { id: 3, title: "ChatGPT layout design", date: "Yesterday" },
  { id: 4, title: "Python data analysis", date: "Yesterday" },
  { id: 5, title: "API integration help", date: "Last 7 days" },
  { id: 6, title: "Debugging JavaScript", date: "Last 7 days" },
  { id: 7, title: "Learning TypeScript", date: "Last 7 days" },
  { id: 8, title: "CSS Flexbox issues", date: "Last 7 days" },
  { id: 9, title: "Node.js server setup", date: "Last 7 days" },
  { id: 10, title: "Database schema design", date: "Last 7 days" },
  { id: 11, title: "Testing React components", date: "Last 7 days" },
  { id: 12, title: "React hooks tutorial", date: "Last 7 days" },
  { id: 13, title: "State management options", date: "Last 7 days" },
  { id: 14, title: "Performance optimization", date: "Last 7 days" },
  { id: 15, title: "Accessibility best practices", date: "Last 7 days" },
  { id: 16, title: "Responsive design tips", date: "Last 7 days" },
  { id: 17, title: "Webpack configuration", date: "Last 7 days" },
  { id: 18, title: "GraphQL basics", date: "Last 7 days" },
  { id: 19, title: "Next.js features", date: "Last 7 days" },
  { id: 20, title: "Deploying to Vercel", date: "Last 7 days" },
  { id: 21, title: "Testing React components", date: "Last 7 days" },
  { id: 22, title: "React hooks tutorial", date: "Last 7 days" },
  { id: 23, title: "State management options", date: "Last 7 days" },
  { id: 24, title: "Performance optimization", date: "Last 7 days" },
  { id: 25, title: "Accessibility best practices", date: "Last 7 days" },
  { id: 26, title: "Responsive design tips", date: "Last 7 days" },
  { id: 27, title: "Webpack configuration", date: "Last 7 days" },
  { id: 28, title: "GraphQL basics", date: "Last 7 days" },
  { id: 29, title: "Next.js features", date: "Last 7 days" },
  { id: 30, title: "Deploying to Vercel", date: "Last 7 days" },
];
